apiVersion: v1
kind: Service
metadata:
    name: "akswithapimsea-a88e"
    labels:
        app: "akswithapimsea-a88e"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "akswithapimsea-a88e"